# Generated by Django 4.2.3 on 2024-01-16 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0034_alter_clearanceform_boys_hostel_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearanceform',
            old_name='csit_hod_approval_date',
            new_name='hod_approval_date',
        ),
        migrations.RenameField(
            model_name='clearanceform',
            old_name='csit_hod_approved_by',
            new_name='hod_approved_by',
        ),
        migrations.RenameField(
            model_name='clearanceform',
            old_name='csit_hod_comment',
            new_name='hod_comment',
        ),
        migrations.RenameField(
            model_name='clearanceform',
            old_name='csit_hod_review',
            new_name='hod_review',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='eed_hod_approval_date',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='eed_hod_approved_by',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='eed_hod_comment',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='eed_hod_review',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='iset_hod_approval_date',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='iset_hod_approved_by',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='iset_hod_comment',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='iset_hod_review',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='mect_hod_approval_date',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='mect_hod_approved_by',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='mect_hod_comment',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='mect_hod_review',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='mpre_hod_approval_date',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='mpre_hod_approved_by',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='mpre_hod_comment',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='mpre_hod_review',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='peg_hod_approval_date',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='peg_hod_approved_by',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='peg_hod_comment',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='peg_hod_review',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='pmbs_hod_approval_date',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='pmbs_hod_approved_by',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='pmbs_hod_comment',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='pmbs_hod_review',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='pngpd_hod_approval_date',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='pngpd_hod_approved_by',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='pngpd_hod_comment',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='pngpd_hod_review',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='slt_hod_approval_date',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='slt_hod_approved_by',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='slt_hod_comment',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='slt_hod_review',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='woet_hod_approval_date',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='woet_hod_approved_by',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='woet_hod_comment',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='woet_hod_review',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile-pics/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_card',
            field=models.ImageField(null=True, upload_to='id-img', verbose_name='ID card'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='matric_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile-pics/', verbose_name='Passport photo'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_file',
            field=models.FileField(null=True, upload_to='student-file/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_reciept',
            field=models.FileField(null=True, upload_to='student-receipt/'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='department',
            field=models.CharField(choices=[('Computer Science and Information Technology', 'Computer Science and Information Technology'), ('Mechanical Engineering Technology', 'Mechanical Engineering Technology'), ('Electrical Engineering', 'Electrical Engineering'), ('Industrial Safety', 'Industrial Safety'), ('Environmental Technology', 'Environmental Technology'), ('Mineral and Petroleum Resources', 'Mineral and Petroleum Resources'), ('Petroleum and Natural Gas Processing Technology', 'Petroleum and Natural Gas Processing Technology'), ('Petroleum Engineering and Geoscience', 'Petroleum Engineering and Geoscience'), ('Petroleum Marketing and Business Studies', 'Petroleum Marketing and Business Studies'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Welding Engineering and Offshore Technology', 'Welding Engineering and Offshore Technology'), ('Computer Engineering Technoloy', 'Computer Engineering Technoloy'), ('Mechatronics', 'Mechatronics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('Computer Science and Information Technology', 'Computer Science and Information Technology'), ('Mechanical Engineering Technology', 'Mechanical Engineering Technology'), ('Electrical Engineering', 'Electrical Engineering'), ('Industrial Safety', 'Industrial Safety'), ('Environmental Technology', 'Environmental Technology'), ('Mineral and Petroleum Resources', 'Mineral and Petroleum Resources'), ('Petroleum and Natural Gas Processing Technology', 'Petroleum and Natural Gas Processing Technology'), ('Petroleum Engineering and Geoscience', 'Petroleum Engineering and Geoscience'), ('Petroleum Marketing and Business Studies', 'Petroleum Marketing and Business Studies'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Welding Engineering and Offshore Technology', 'Welding Engineering and Offshore Technology'), ('Computer Engineering Technoloy', 'Computer Engineering Technoloy'), ('Mechatronics', 'Mechatronics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='state_of_origin',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'AkwaIbom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Kastina', 'Kastina'), ('Kebbi', 'Kebbi'), ('kogi', 'kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfarawa', 'Zamfarawa')], max_length=50, null=True),
        ),
    ]
